baseURL = "https://tmccormick92.com/"
languageCode = "en-us"
title = "Trevor's Notes"
theme = "ghostwriter"
[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "mydeployment"
#S3
URL = "s3://tmccormick92.com/?region=us-east-2"
cloudFrontDistributionId = "ENXDKV0O7A0QX"
